name: GPU Test Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      - self-hosted
      - codebuild-gpu-runner-${{ github.run_id }}-${{ github.run_attempt }}
    container:
      image: 381492037974.dkr.ecr.us-east-1.amazonaws.com/codebuild-cuda12:latest
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: Run GPU Tests
        run: |
          nvidia-smi
          nvcc --version
