name: GPU Test Workflow
on: [push]
jobs:
  build:
    runs-on:
      - codebuild-gpu-test-4-${{ github.run_id }}-${{ github.run_attempt }}
      - image:381492037974.dkr.ecr.us-east-1.amazonaws.com/codebuild-cuda12:latest
      - instance-size:gpu_large
      - buildspec-override:true
    steps:
      - uses: actions/checkout@v3
      - name: Run GPU Tests
        run: |
          echo "This is handled by CodeBuild. See buildspec.yml for execution."
