name: GPU Test Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      - codebuild-gpu-test-4-${{ github.run_id }}-${{ github.run_attempt }}
      - instance-size:gpu_large
    container:
      image: 381492037974.dkr.ecr.us-east-1.amazonaws.com/codebuild-cuda12:latest
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: Show CUDA + Driver Info
        run: |
          echo "---- nvidia-smi ----"
          nvidia-smi || echo "No GPU"
          echo "---- nvcc version ----"
          nvcc --version || echo "nvcc not installed"
