name: GPU Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - codebuild-gpu-test-${{ github.run_id }}-${{ github.run_attempt }}
      - instance-size:gpu_large

    steps:
      - uses: actions/checkout@v3

      - name: Verify Environment
        run: |
          nvidia-smi
          nvcc --version
          
      - name: Compile and Run CUDA Test
        run: |
          nvcc test.cu -o test
          ./test
