name: GPU Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - codebuild-gpu-test-${{ github.run_id }}-${{ github.run_attempt }}
      - image:381492037974.dkr.ecr.us-east-1.amazonaws.com/codebuild-cuda12-test:latest
      - instance-size:gpu_large

    steps:
      - uses: actions/checkout@v3
      
      - name: Verify System Dependencies
        run: |
          echo "=== System Dependencies ==="
          dpkg -l | grep -i icu
          ldconfig -p | grep -i icu
          
      - name: Start Docker daemon
        run: |
          echo "=== Starting Docker Daemon ==="
          sudo dockerd &
          sleep 10
          docker info || true
      
      - name: System Info
        run: |
          echo "=== System Information ==="
          uname -a
          cat /etc/os-release
          
      - name: GPU and CUDA Info
        run: |
          echo "=== GPU Information ==="
          nvidia-smi
          echo "=== CUDA Version ==="
          nvcc --version
          echo "=== CUDA Path ==="
          echo $CUDA_PATH
          ls -l /usr/local/cuda*
