name: GPU Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - codebuild-gpu-test-${{ github.run_id }}-${{ github.run_attempt }}
      - image:381492037974.dkr.ecr.us-east-1.amazonaws.com/codebuild-cuda12-test:latest
      - instance-size:gpu_large

    steps:
      - uses: actions/checkout@v3
      
      - name: Start Docker daemon
        run: |
          sudo systemctl start docker || true
          sudo dockerd &
          sleep 10
          docker info
      
      - name: System Info
        run: |
          echo "=== System Information ==="
          uname -a
          cat /etc/os-release
          
      - name: GPU and CUDA Info
        run: |
          echo "=== GPU Information ==="
          nvidia-smi || echo "nvidia-smi failed"
          echo "=== CUDA Version ==="
          nvcc --version || echo "nvcc not found"
          echo "=== CUDA Path ==="
          echo $CUDA_PATH
          ls -l /usr/local/cuda* || echo "CUDA directory not found"
          
      - name: Test CUDA Program
        run: |
          echo "=== Running CUDA Test Program ==="
          /tmp/test || echo "CUDA test program failed"
          
      - name: Environment Variables
        run: |
          echo "=== Environment Variables ==="
          env | grep -i cuda
          
      - name: Docker Info
        run: |
          echo "=== Docker Information ==="
          docker info || echo "Docker info failed"
          docker --version || echo "Docker version failed"

      - name: Compile CUDA Test
        run: |
          echo "=== Compiling CUDA Test ==="
          nvcc test.cu -o cuda_test || echo "CUDA compilation failed"
          
      - name: Run CUDA Test
        run: |
          echo "=== Running CUDA Test ==="
          ./cuda_test || echo "CUDA test execution failed"
